#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Starship Shell Prompt
export STARSHIP_CONFIG="$HOME/.config/starship/config.toml"

export GOPATH="$HOME/source/go"

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="$(go env GOPATH)/bin:$PATH"
. "$HOME/.cargo/env"

# Windows paths
export PATH="$PATH:/mnt/d/Programs/Microsoft VS Code/bin"
export PATH="$PATH:/mnt/c/Program Files/Oracle/VirtualBox"
export PATH="$PATH:/mnt/c/WINDOWS/System32"

export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
export VAGRANT_WSL_WINDOWS_ACCESS_USER_HOME_PATH="/mnt/c/Users/jniec/.kitchen"

export EDITOR="nvim"
export GH_EDITOR="nvim"
export TERM="xterm-256color"

# tell 'less' to not paginate if less than a page
export LESS="-F -X $LESS"

# enable gpg signing
export GPG_TTY=$(tty)

# silence keybase path warnings
export KEYBASE_PATH_WARNING=0

# for WSL2, use dokken file for test kitchen 
export KITCHEN_LOCAL_YAML=.kitchen.dokken.yml

# tfenv, don't auto install
export TFENV_AUTO_INSTALL=false
